"""C09 — escrow: the Conditional Work Exchange conventions (spec §9.3, §9.4, §9.6).

Single-arbiter milestones, the k-of-n rung construction with signed votes,
split awards, decision-neutral fees, deadline arithmetic, and
commit-then-accept — all built from the unmodified §3.4 lock primitive
against an ordinary C06 mint.  Locked decision L15 applies throughout.

No joint secrets anywhere (L15 — grep-level review point):
every 32-byte preimage in this module is generated by ``new_secret()`` in
exactly one place and held by exactly one party:

  * rung preimages ``a_{j,m,r}``   — ``Arbiter.attest_rungs`` (arbiter j only)
  * fee preimages ``f_{j,m}``      — ``Arbiter.attest_rungs`` (arbiter j only)
  * refund secrets ``r_m``         — ``EscrowPayer.fund`` (payer only,
                                     one fresh secret per milestone — req 7)
  * payee/fee-account output secrets — ``EscrowPayee.generate_output_hashes``
                                     (that holder only)
  * §9.4 acceptance preimage + refund secret — ``CommitThenAccept.payer_commit``
                                     (payer only)
  * §9.4 worker output secret      — ``CommitThenAccept.worker_hash``
                                     (worker only)

Nothing is ever derived from, split out of, or shared between these; the
quorum rule is a signed-vote convention among arbiters (R10), and any
defection from it is bounded to value/n and provable against the
defector's signed vote.

Decision-neutral fees (requirement 5, asserted structurally): a fee
attestation's preimage is generated independently of every rung preimage,
``EscrowPayer.fund`` refuses any attestation set in which two attested
outputs share a preimage hash (so a fee output locked to a milestone
release preimage is impossible through this API), and
``EscrowPayee.verify_funding`` re-checks the same disjointness.

Time discipline (L17): this module never reads wall time.  The only
temporal check performed client-side — the §9.4 reveal deadline — uses
``mint_time`` as reported by the mint's own ``/v3/status`` response.
Everything else is deadline *arithmetic* (no clock) or is enforced by the
mint's commit-time lock evaluation.

Fractions: awards travel as exact integer ratios (``award_num`` /
``award_den``).  Floats are refused ("no floats, ever" — §3.1 ethos and
§3.3 canonical JSON).
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass
from fractions import Fraction

from aicash.burncalc import BurnPolicy, compute_burn, effective_policy
from aicash.receipts import make_dispute_record as _c12_make_dispute_record
from aicash.signing import attach_sig, generate_keypair, verify_obj
from aicash.tokencodec import (
    TokenError,
    b64u_decode,
    b64u_encode,
    canonical_json,
    format_token,
    ledger_key,
    new_secret,
    parse_token,
)

__all__ = [
    "EscrowError",
    "DeadlineError",
    "FundingInvalid",
    "QuorumNotMet",
    "RevealInvalid",
    "LateReveal",
    "FundingInfo",
    "compute_deadlines",
    "evidence_hash",
    "rung_composition",
    "Arbiter",
    "EscrowPayer",
    "EscrowPayee",
    "CommitThenAccept",
    "make_dispute_record",
]

SCHEMA_V = 4

#: The rung-key marker for a decision-neutral fee output.
FEE_RUNG = "fee"


# ---------------------------------------------------------------------------
# exceptions
# ---------------------------------------------------------------------------


class EscrowError(Exception):
    """Base class for every §9.3/§9.4 convention violation."""


class DeadlineError(EscrowError):
    """Deadline ordering that would re-enable refund-after-delivery."""


class FundingInvalid(EscrowError):
    """§9.3 mandatory funding verification failed.  The message and the
    ``milestone`` / ``arbiter_id`` / ``rung`` / ``reason`` attributes name
    the offending output (requirement 2)."""

    def __init__(self, reason: str, milestone=None, arbiter_id=None, rung=None):
        self.reason = reason
        self.milestone = milestone
        self.arbiter_id = arbiter_id
        self.rung = rung
        where = ""
        if milestone is not None:
            where = f" at milestone {milestone}, arbiter {arbiter_id!r}, rung {rung}"
        super().__init__(f"funding invalid{where}: {reason}")


class QuorumNotMet(EscrowError):
    """``Arbiter.reveal`` refused: fewer than k valid signed votes for this
    (job, milestone, evidence, award) were supplied (requirement 3)."""


class RevealInvalid(EscrowError):
    """A revealed preimage does not open the verified funded lock."""


class LateReveal(EscrowError):
    """§9.4: the payer tried to reveal after ``expiry − grace − margin``;
    the attempt is recorded as a refusal (requirement 6)."""


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------


def _sha256_b64u(data: bytes) -> str:
    return b64u_encode(hashlib.sha256(data).digest())


def evidence_hash(evidence) -> str:
    """b64u(sha256(canonical_json(evidence))) — what votes bind to (B7)."""
    return _sha256_b64u(canonical_json(evidence))


def _require_ms(name: str, value, minimum: int = 0) -> int:
    if type(value) is not int:
        raise DeadlineError(f"{name} must be a plain integer (ms)")
    if value < minimum:
        raise DeadlineError(f"{name} must be >= {minimum}")
    return value


def compute_deadlines(
    evidence_deadline: int,
    decision_deadline: int,
    grace_ms: int,
    settlement_margin: int,
) -> int:
    """Return the minimum conformant lock expiry ``T_m`` for a milestone.

    Enforces the §9.3 ordering that makes refund-after-delivery impossible:

        evidence_deadline < decision_deadline
        T_m >= decision_deadline + grace_ms + settlement_margin

    A payee who receives the release preimages at the worst allowed moment
    (exactly ``decision_deadline``) still has ``grace_ms +
    settlement_margin`` of mint time before the refund path opens, and its
    claim submission stays outside the §3.4 ``grace_ms`` client convention.
    ``settlement_margin`` must be at least 1 ms — with a zero margin a
    reveal exactly at the decision deadline could land at ``mint_time ==
    expiry``, which belongs to the refund path (R3).  Raises
    ``DeadlineError`` on any ordering that would break the guarantee (B2).
    """
    _require_ms("evidence_deadline", evidence_deadline)
    _require_ms("decision_deadline", decision_deadline)
    _require_ms("grace_ms", grace_ms)
    _require_ms("settlement_margin", settlement_margin, minimum=1)
    if decision_deadline <= evidence_deadline:
        raise DeadlineError(
            "decision_deadline must be strictly after evidence_deadline"
        )
    return decision_deadline + grace_ms + settlement_margin


def rung_composition(total_mc: int, denoms_desc) -> list[int]:
    """§9.6 ladder composition for a rung set, "so fractional awards
    compose cleanly": greedy over the denominations, then one coin of each
    denomination above the smallest is broken into the next rung down.
    E.g. 9,000 over (1000, 100, 10) → 8×1000 + 9×100 + 10×10."""
    denoms = sorted({int(d) for d in denoms_desc}, reverse=True)
    if not denoms or any(d <= 0 for d in denoms):
        raise EscrowError("denominations must be positive integers")
    counts = {}
    remaining = int(total_mc)
    for d in denoms:
        counts[d], remaining = divmod(remaining, d)
    if remaining:
        raise EscrowError(
            f"{total_mc} mc is not representable in denominations {denoms}"
        )
    for i, d in enumerate(denoms[:-1]):
        nxt = denoms[i + 1]
        if d % nxt:
            raise EscrowError("denominations must form a ladder")
        if counts[d] > 0:
            counts[d] -= 1
            counts[nxt] += d // nxt
    out: list[int] = []
    for d in denoms:
        out.extend([d] * counts[d])
    return out


def _as_fraction(value) -> Fraction:
    """Normalize a decision/award to an exact ``Fraction`` in [0, 1].

    Accepts "release" (== 1), "refund" (== 0), an int 0/1, a ``Fraction``,
    or an exact ``(numerator, denominator)`` tuple.  Floats are refused."""
    if value == "release":
        return Fraction(1)
    if value == "refund":
        return Fraction(0)
    if isinstance(value, Fraction):
        f = value
    elif isinstance(value, bool):
        raise EscrowError("decision must not be a bool")
    elif isinstance(value, int):
        f = Fraction(value)
    elif isinstance(value, tuple) and len(value) == 2:
        f = Fraction(value[0], value[1])
    else:
        raise EscrowError(
            'decision must be "release", "refund", a Fraction, or a'
            " (num, den) tuple — floats are refused (no floats, ever)"
        )
    if not (0 <= f <= 1):
        raise EscrowError("award fraction must be within [0, 1]")
    return f


def _policy_from_descriptor(desc: dict) -> BurnPolicy:
    """The burn policy in force per the mint's own clock (never wall time)."""
    bp = desc["burn_policy"]
    current = BurnPolicy(
        rate_ppm=bp["rate_ppm"],
        cap_mc=bp["cap_mc"],
        exempt_below_mc=bp["exempt_below_mc"],
    )
    nxt = desc.get("burn_policy_next")
    next_t = None
    if nxt is not None:
        np = nxt["policy"]
        next_t = (
            BurnPolicy(
                rate_ppm=np["rate_ppm"],
                cap_mc=np["cap_mc"],
                exempt_below_mc=np["exempt_below_mc"],
            ),
            nxt["effective_at"],
        )
    return effective_policy(current, next_t, desc["mint_time"])


def _status_chunked(client, hashes: list[str], max_batch: int) -> list[dict]:
    results: list[dict] = []
    step = max(1, int(max_batch))
    for i in range(0, len(hashes), step):
        _mt, part = client.status(hashes[i : i + step])
        results.extend(part)
    return results


def _attestation_key(a: dict):
    return (a["milestone"], a["arbiter_id"], a["rung"])


# ---------------------------------------------------------------------------
# FundingInfo — the public (secret-free) description of a funded job
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FundingInfo:
    """What the payer hands the payee after funding: the by-hash output
    layout.  Contains no secrets of any kind — the refund secrets stay with
    the payer, the output secrets with their holders, the rung preimages
    with the arbiters.

    ``outputs`` entries: ``{milestone, arbiter_id, rung, amount_mc,
    secret_hash, preimage_hash, expiry}``.

    Wire form (payer→payee across a process boundary): ``to_dict()``
    returns a canonical-JSON-safe dict — string keys throughout (milestone
    keys of ``expiries`` become decimal strings), hash fields already b64u
    strings, no floats anywhere — suitable for
    ``tokencodec.canonical_json``; ``from_dict()`` parses it back.
    ``EscrowPayee.verify_funding`` accepts either form.
    """

    job_id: str
    mint_id: str
    outputs: tuple
    expiries: dict
    burn_mc: int = 0
    change_mc: int = 0

    _OUTPUT_FIELDS = (
        "milestone",
        "arbiter_id",
        "rung",
        "amount_mc",
        "secret_hash",
        "preimage_hash",
        "expiry",
    )

    def to_dict(self) -> dict:
        """The canonical-JSON-safe wire form of the funding handoff.

        Exactly the keys ``job_id``, ``mint_id``, ``outputs``,
        ``expiries``, ``burn_mc``, ``change_mc``; ``expiries`` keys are
        the milestone numbers as decimal strings (canonical JSON requires
        string object keys).  Secret-free by construction — FundingInfo
        carries only public, by-hash material.
        """
        return {
            "job_id": self.job_id,
            "mint_id": self.mint_id,
            "outputs": [dict(o) for o in self.outputs],
            "expiries": {str(m): t for m, t in self.expiries.items()},
            "burn_mc": self.burn_mc,
            "change_mc": self.change_mc,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "FundingInfo":
        """Parse the ``to_dict`` wire form back into a FundingInfo.

        Validates the wire shape (exact top-level keys, plain-int amounts
        and expiries, 32-byte b64u hash fields, int-or-"fee" rungs,
        decimal-string milestone keys) and raises ``EscrowError`` on any
        deviation.  The §9.3 semantic verification — signatures, ledger
        state, attested hashes — remains ``verify_funding``'s job.
        """
        if not isinstance(d, dict):
            raise EscrowError("funding wire form must be a dict")
        expected = {
            "job_id", "mint_id", "outputs", "expiries", "burn_mc", "change_mc",
        }
        if set(d) != expected:
            raise EscrowError(
                "funding wire form must have exactly the keys %s"
                % sorted(expected)
            )
        if not isinstance(d["job_id"], str) or not isinstance(d["mint_id"], str):
            raise EscrowError("job_id and mint_id must be strings")
        if not isinstance(d["outputs"], (list, tuple)):
            raise EscrowError("outputs must be a list")
        outputs = []
        for o in d["outputs"]:
            if not isinstance(o, dict) or set(o) != set(cls._OUTPUT_FIELDS):
                raise EscrowError(
                    "each output must be a dict with exactly the keys %s"
                    % (cls._OUTPUT_FIELDS,)
                )
            for name in ("milestone", "amount_mc", "expiry"):
                if type(o[name]) is not int:
                    raise EscrowError(f"output {name} must be a plain int")
            if not isinstance(o["arbiter_id"], str):
                raise EscrowError("output arbiter_id must be a string")
            if o["rung"] != FEE_RUNG and type(o["rung"]) is not int:
                raise EscrowError(
                    f'output rung must be an int or "{FEE_RUNG}"'
                )
            for name in ("secret_hash", "preimage_hash"):
                try:
                    b64u_decode(o[name], expect_len=32)
                except TokenError:
                    raise EscrowError(
                        f"output {name} must be a 32-byte b64u hash"
                    ) from None
            outputs.append(dict(o))
        if not isinstance(d["expiries"], dict):
            raise EscrowError("expiries must be a dict")
        expiries = {}
        for k, v in d["expiries"].items():
            if not isinstance(k, str) or not k.isdigit() or str(int(k)) != k:
                raise EscrowError(
                    "expiries keys must be canonical decimal strings"
                )
            if type(v) is not int:
                raise EscrowError("expiries values must be plain ints")
            expiries[int(k)] = v
        for name in ("burn_mc", "change_mc"):
            if type(d[name]) is not int or d[name] < 0:
                raise EscrowError(f"{name} must be a non-negative int")
        return cls(
            job_id=d["job_id"],
            mint_id=d["mint_id"],
            outputs=tuple(outputs),
            expiries=expiries,
            burn_mc=d["burn_mc"],
            change_mc=d["change_mc"],
        )


# ---------------------------------------------------------------------------
# Arbiter — one instance per panel member (holds its OWN preimages + key)
# ---------------------------------------------------------------------------


class Arbiter:
    """One panel member: its own rung preimages, its own fee preimages, its
    own Ed25519 signing key (C05).  Nothing here is ever shared (L15).

    Single-arbiter milestones are the ``k=1, n=1`` degenerate panel: the
    arbiter's own signed vote is the rendered decision, so even a solo
    release leaves a signed record.
    """

    def __init__(self, arbiter_id: str, keypair: tuple[bytes, bytes] | None = None):
        if not isinstance(arbiter_id, str) or not arbiter_id:
            raise EscrowError("arbiter_id must be a non-empty string")
        if keypair is None:
            keypair = generate_keypair()
        self.arbiter_id = arbiter_id
        self._private, self.public = keypair
        self.k = 1
        self.panel_pubs: dict[str, bytes] = {arbiter_id: self.public}
        self._rungs: dict[tuple, list] = {}  # (job, m) -> [(rung, amount, preimage)]
        self._fees: dict[tuple, tuple] = {}  # (job, m) -> (amount, preimage)

    def set_panel(self, k: int, panel_pubs: dict) -> None:
        """Configure the quorum rule: ``k`` signed votes out of the named
        panel members (arbiter_id → Ed25519 public key)."""
        if type(k) is not int or k < 1:
            raise EscrowError("k must be a positive integer")
        if not isinstance(panel_pubs, dict) or self.arbiter_id not in panel_pubs:
            raise EscrowError("panel_pubs must include this arbiter")
        if k > len(panel_pubs):
            raise EscrowError("k cannot exceed the panel size")
        self.k = k
        self.panel_pubs = dict(panel_pubs)

    # -- attestation -----------------------------------------------------

    def attest_rungs(
        self, job_id: str, m: int, rung_values: list[int], fee_mc: int = 0
    ) -> list[dict]:
        """Generate this arbiter's OWN rung preimages (and, when
        ``fee_mc > 0``, its decision-neutral fee preimage) for milestone
        ``m`` and return the signed attestations
        ``{job_id, milestone, rung, amount_mc, preimage_hash}`` (§9.3) —
        each hash attested by the one party that holds its preimage."""
        key = (job_id, m)
        if key in self._rungs:
            raise EscrowError("rungs for this (job, milestone) already attested")
        if type(m) is not int or m < 0:
            raise EscrowError("milestone must be a non-negative integer")
        if type(fee_mc) is not int or fee_mc < 0:
            raise EscrowError("fee_mc must be a non-negative integer")
        rungs = []
        attestations = []
        for r, value in enumerate(rung_values):
            if type(value) is not int or value <= 0:
                raise EscrowError("rung values must be positive integers")
            preimage = new_secret()
            rungs.append((r, value, preimage))
            attestations.append(self._attest(job_id, m, r, value, preimage))
        self._rungs[key] = rungs
        if fee_mc > 0:
            # The fee preimage is a FRESH independent secret — never derived
            # from or equal to any rung preimage (requirement 5).
            fee_preimage = new_secret()
            self._fees[key] = (fee_mc, fee_preimage)
            attestations.append(
                self._attest(job_id, m, FEE_RUNG, fee_mc, fee_preimage)
            )
        return attestations

    def _attest(self, job_id, m, rung, amount_mc, preimage) -> dict:
        return attach_sig(
            {
                "kind": "attestation",
                "v": SCHEMA_V,
                "job_id": job_id,
                "milestone": m,
                "arbiter_id": self.arbiter_id,
                "rung": rung,
                "amount_mc": amount_mc,
                "preimage_hash": _sha256_b64u(preimage),
            },
            self._private,
        )

    # -- voting ----------------------------------------------------------

    def vote(self, job_id: str, m: int, evidence, decision) -> dict:
        """A signed vote over the delivery evidence, bound to
        ``(job_id, milestone, evidence_hash)`` (B7).  ``decision`` is
        "release", "refund", or an exact fraction for a split award."""
        f = _as_fraction(decision)
        body = {
            "kind": "vote",
            "v": SCHEMA_V,
            "job_id": job_id,
            "milestone": m,
            "arbiter_id": self.arbiter_id,
            "evidence_hash": evidence_hash(evidence),
            "decision": "release" if f == 1 else "refund" if f == 0 else "split",
            "award_num": f.numerator,
            "award_den": f.denominator,
        }
        return attach_sig(body, self._private)

    def _count_quorum(self, job_id, m, awarded: Fraction, votes) -> int:
        """Largest set of valid signed votes for exactly this
        (job, milestone, award) from distinct panel members over ONE common
        evidence hash — votes bound to different evidence never combine."""
        by_evidence: dict[str, set] = {}
        for v in votes:
            if not isinstance(v, dict):
                continue
            aid = v.get("arbiter_id")
            pub = self.panel_pubs.get(aid)
            if pub is None:
                continue
            if v.get("job_id") != job_id or v.get("milestone") != m:
                continue
            num, den = v.get("award_num"), v.get("award_den")
            if (
                type(num) is not int
                or type(den) is not int
                or den < 1
                or Fraction(num, den) != awarded
            ):
                continue
            eh = v.get("evidence_hash")
            if not isinstance(eh, str):
                continue
            if not verify_obj(v, pub):
                continue
            by_evidence.setdefault(eh, set()).add(aid)
        return max((len(s) for s in by_evidence.values()), default=0)

    # -- reveal ----------------------------------------------------------

    def reveal(
        self,
        job_id: str,
        m: int,
        awarded_fraction,
        votes=(),
        force: bool = False,
    ) -> dict:
        """Reveal this arbiter's preimages for the awarded share of its
        rungs, plus its decision-neutral fee preimage (a decision — any
        decision — was rendered).

        Convention (requirement 3): refuses with ``QuorumNotMet`` unless
        ``votes`` contains ``k`` valid signed votes from distinct panel
        members for exactly this award over one evidence hash.
        ``force=True`` is a TEST-ONLY defection model: it skips the refusal
        but never silently — the returned reveal record carries the honest
        ``quorum`` flag, so a forced reveal is self-documenting evidence of
        defection (B4).  Production callers must not pass it.
        """
        awarded = _as_fraction(awarded_fraction)
        key = (job_id, m)
        rungs = self._rungs.get(key, [])
        if key not in self._rungs and key not in self._fees:
            raise EscrowError("nothing attested for this (job, milestone)")
        count = self._count_quorum(job_id, m, awarded, votes)
        quorum = count >= self.k
        if not quorum and not force:
            raise QuorumNotMet(
                f"{count} valid signed vote(s) for this award, need {self.k}"
            )
        total = sum(v for _r, v, _p in rungs)
        awarded_amount = total * awarded
        if awarded_amount.denominator != 1:
            raise EscrowError(
                "awarded fraction of the rung-set value is not an integer"
            )
        remaining = int(awarded_amount)
        preimages = []
        for r, value, preimage in sorted(rungs, key=lambda t: (-t[1], t[0])):
            if value <= remaining:
                remaining -= value
                preimages.append(
                    {"rung": r, "amount_mc": value, "preimage": b64u_encode(preimage)}
                )
        if remaining:
            raise EscrowError(
                "awarded fraction does not compose exactly from the rung"
                " denominations (§9.3 split-award ladder)"
            )
        fee = self._fees.get(key)
        if fee is not None:
            fee_mc, fee_preimage = fee
            preimages.append(
                {
                    "rung": FEE_RUNG,
                    "amount_mc": fee_mc,
                    "preimage": b64u_encode(fee_preimage),
                }
            )
        return {
            "job_id": job_id,
            "milestone": m,
            "arbiter_id": self.arbiter_id,
            "award_num": awarded.numerator,
            "award_den": awarded.denominator,
            "quorum": quorum,
            "votes": list(votes),
            "preimages": preimages,
        }

    # -- records ---------------------------------------------------------

    def sign_dispute(self, record: dict) -> dict:
        """Sign a §10.2 dispute-outcome record as this arbiter (C12)."""
        from aicash.receipts import sign_dispute

        return sign_dispute(record, self._private, self.arbiter_id)


# ---------------------------------------------------------------------------
# EscrowPayer — funds by-hash locked outputs, refunds at expiry
# ---------------------------------------------------------------------------


class EscrowPayer:
    """The payer side of one §9.3 escrow job.

    Holds the funding tokens, generates one fresh refund secret per
    milestone (requirement 7 — and only the payer ever holds them), funds
    every attested output by hash, and refunds whatever is still unspent
    once a milestone's expiry passes.
    """

    def __init__(
        self,
        client,
        mint_id: str,
        funding_tokens: list[str],
        settlement_margin_ms: int = 60_000,
        arbiter_pubs: dict | None = None,
    ):
        self._client = client
        self._mint_id = mint_id
        self._tokens = list(funding_tokens)
        self._margin = _require_ms("settlement_margin", settlement_margin_ms, 1)
        self._arbiter_pubs = dict(arbiter_pubs) if arbiter_pubs else None
        self._refund_secrets: dict[int, bytes] = {}
        self._funded: list[dict] | None = None
        self._holdings: list[tuple[bytes, int]] = []  # (secret, amount)

    def balance(self) -> int:
        """Plain value held back by the payer (change + refunds), net."""
        return sum(a for _s, a in self._holdings)

    def fund(
        self,
        job_id: str,
        milestones: list[dict],
        attestations: list[dict],
        payee_hashes: dict,
        expiries: dict,
    ) -> FundingInfo:
        """Fund the whole job in one ``/v3/exchange`` call: one by-hash
        locked output per signed attestation, expiries per milestone,
        distinct refund secrets per milestone.

        ``milestones``: ``[{m, evidence_deadline, decision_deadline}, ...]``
        — deadline ordering is enforced HERE, at fund time (requirement 6):
        each ``expiries[m]`` must satisfy ``compute_deadlines``.

        ``payee_hashes``: ``{(m, arbiter_id, rung): secret_hash}`` — rung
        output hashes from the payee, fee output hashes from the panel's
        fee account.  The payer never learns any output secret.

        Structural fee-neutrality assert (requirement 5): any two attested
        outputs sharing a preimage hash — in particular a fee output locked
        to a milestone release preimage — are refused outright.
        """
        if self._funded is not None:
            raise EscrowError("fund() already called for this job")
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        grace_ms = desc["lock_params"]["grace_ms"]
        max_batch = desc["limits"]["max_batch"]

        # Requirement 6: deadline ordering enforced at fund time.
        known_m = set()
        for spec in milestones:
            m = spec["m"]
            known_m.add(m)
            if m not in expiries:
                raise DeadlineError(f"no expiry given for milestone {m}")
            min_expiry = compute_deadlines(
                spec["evidence_deadline"],
                spec["decision_deadline"],
                grace_ms,
                self._margin,
            )
            if expiries[m] < min_expiry:
                raise DeadlineError(
                    f"milestone {m} expiry {expiries[m]} is below the"
                    f" conformant minimum {min_expiry}"
                    " (decision_deadline + grace_ms + settlement_margin)"
                )

        # Validate the attestation set.
        seen_hashes: set[str] = set()
        seen_keys: set[tuple] = set()
        records: list[dict] = []
        for a in attestations:
            if not isinstance(a, dict) or a.get("kind") != "attestation":
                raise EscrowError("attestations must be signed attestation dicts")
            m = a["milestone"]
            if m not in known_m:
                raise EscrowError(f"attestation for unknown milestone {m}")
            if self._arbiter_pubs is not None:
                pub = self._arbiter_pubs.get(a["arbiter_id"])
                if pub is None or not verify_obj(a, pub):
                    raise EscrowError(
                        f"attestation signature invalid for milestone {m},"
                        f" arbiter {a.get('arbiter_id')!r}, rung {a.get('rung')}"
                    )
            h = a["preimage_hash"]
            if h in seen_hashes:
                raise EscrowError(
                    "attested preimage hashes must be pairwise distinct — a"
                    " fee output can never be locked to a milestone release"
                    " preimage, and no two rungs may share one (L15/§9.3)"
                )
            seen_hashes.add(h)
            key = _attestation_key(a)
            if key in seen_keys:
                raise EscrowError(f"duplicate attestation for {key}")
            seen_keys.add(key)
            if key not in payee_hashes:
                raise EscrowError(f"no output secret hash supplied for {key}")
            records.append(
                {
                    "milestone": m,
                    "arbiter_id": a["arbiter_id"],
                    "rung": a["rung"],
                    "amount_mc": a["amount_mc"],
                    "secret_hash": payee_hashes[key],
                    "preimage_hash": h,
                    "expiry": expiries[m],
                }
            )

        # Requirement 7: one fresh refund secret per milestone, payer-held.
        for m in sorted(known_m):
            self._refund_secrets[m] = new_secret()

        escrow_total = sum(r["amount_mc"] for r in records)
        input_sum = 0
        for t in self._tokens:
            tok = parse_token(t)
            if tok.mint_id != self._mint_id:
                raise EscrowError("funding token from a different mint")
            input_sum += tok.amount_mc
        burn = compute_burn(input_sum, policy)
        change = input_sum - escrow_total - burn
        if change < 0:
            raise EscrowError(
                f"funding tokens cover {input_sum} mc but the job needs"
                f" {escrow_total} mc + {burn} mc burn"
            )
        outputs = [
            {
                "amount_mc": r["amount_mc"],
                "secret_hash": r["secret_hash"],
                "lock": {
                    "preimage_hash": r["preimage_hash"],
                    "expiry": r["expiry"],
                    "refund_hash": _sha256_b64u(
                        self._refund_secrets[r["milestone"]]
                    ),
                },
            }
            for r in records
        ]
        change_secret = None
        if change > 0:
            change_secret = new_secret()
            outputs.append(
                {
                    "amount_mc": change,
                    "secret_hash": ledger_key(change_secret),
                    "lock": None,
                }
            )
        if len(self._tokens) + len(outputs) > max_batch:
            raise EscrowError(
                "job does not fit in one exchange call (limits.max_batch);"
                " fund per milestone with per-milestone token splits"
            )
        self._client.exchange(str(uuid.uuid4()), list(self._tokens), outputs)
        if change_secret is not None:
            self._holdings.append((change_secret, change))
        self._funded = records
        self._job_id = job_id
        return FundingInfo(
            job_id=job_id,
            mint_id=self._mint_id,
            outputs=tuple(dict(r) for r in records),
            expiries=dict(expiries),
            burn_mc=burn,
            change_mc=change,
        )

    def refund_expired(self, m: int) -> int:
        """Refund every still-unspent output of milestone ``m`` via the
        §3.4 refund path (ledger hash + this milestone's refund secret; no
        token secret — L5).  The mint enforces ``mint_time >= expiry``.
        Returns the net amount recovered (0 when nothing was refundable)."""
        if self._funded is None:
            raise EscrowError("nothing funded")
        if m not in self._refund_secrets:
            raise EscrowError(f"unknown milestone {m}")
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        max_batch = desc["limits"]["max_batch"]
        mine = [r for r in self._funded if r["milestone"] == m]
        hashes = [r["secret_hash"] for r in mine]
        results = _status_chunked(self._client, hashes, max_batch)
        unspent = [
            r
            for r, res in zip(mine, results)
            if res.get("state") == "unspent"
        ]
        if not unspent:
            return 0
        witness = b64u_encode(self._refund_secrets[m])
        inputs = [{"hash": r["secret_hash"], "witness": witness} for r in unspent]
        total = sum(r["amount_mc"] for r in unspent)
        burn = compute_burn(total, policy)
        net = total - burn
        fresh = new_secret()
        outputs = (
            [{"amount_mc": net, "secret_hash": ledger_key(fresh), "lock": None}]
            if net > 0
            else []
        )
        self._client.exchange(str(uuid.uuid4()), inputs, outputs)
        if net > 0:
            self._holdings.append((fresh, net))
        return net


# ---------------------------------------------------------------------------
# EscrowPayee — output-secret holder: MANDATORY funding verification, redeem
# ---------------------------------------------------------------------------


class EscrowPayee:
    """The output-secret-holding side of one escrow job: the payee proper
    (rung outputs) or the panel's fee account (fee outputs — pass
    ``kinds=("fee",)`` to ``generate_output_hashes``)."""

    def __init__(self, client, mint_id: str, arbiter_pubs: dict):
        self._client = client
        self._mint_id = mint_id
        self._arbiter_pubs = dict(arbiter_pubs)
        self._secrets: dict[tuple, bytes] = {}  # (m, arbiter_id, rung) -> secret
        self._pinned: dict[tuple, dict] = {}
        self._verified = False
        self._holdings: list[tuple[bytes, int]] = []

    def balance(self) -> int:
        return sum(a for _s, a in self._holdings)

    def generate_output_hashes(self, attestations, kinds=("rung",)) -> dict:
        """Generate one fresh output secret per attested output of the
        given kinds and return ``{(m, arbiter_id, rung): secret_hash}`` for
        the payer's by-hash funding call.  Only this instance ever holds
        the secrets."""
        out = {}
        for a in attestations:
            kind = FEE_RUNG if a["rung"] == FEE_RUNG else "rung"
            if kind not in kinds:
                continue
            key = _attestation_key(a)
            if key in self._secrets:
                raise EscrowError(f"output secret already generated for {key}")
            secret = new_secret()
            self._secrets[key] = secret
            out[key] = ledger_key(secret)
        return out

    def verify_funding(self, info: FundingInfo | dict, attestations) -> None:
        """The MANDATORY §9.3 pre-work check (requirement 2), complete.

        ``info`` is the payer's handoff: a FundingInfo, or its wire form —
        the ``FundingInfo.to_dict`` canonical-JSON-safe dict as received
        from a stranger payer across a process boundary (parsed via
        ``FundingInfo.from_dict``; a malformed wire dict raises
        ``EscrowError``).

        The checks:

        * every attestation signature verifies against its arbiter's key;
        * attested preimage hashes are pairwise distinct (fee/rung
          disjointness re-checked);
        * the funded output set matches the attested set exactly;
        * every output we hold a secret for is keyed by OUR hash;
        * on the ledger (batch ``/v3/status``): every output exists, is
          unspent, has the attested amount, the agreed expiry, and a lock
          whose ``preimage_hash`` equals the attested value.

        Any failure raises ``FundingInvalid`` naming the offending rung.
        Without this check a payer can fund locks keyed to a preimage of
        its own invention and silently reconstruct refund-after-delivery
        (§9.3, B3).  Nothing is pinned unless every check passes.
        """
        if isinstance(info, dict):
            info = FundingInfo.from_dict(info)
        if not isinstance(info, FundingInfo):
            raise EscrowError("info must be a FundingInfo or its wire dict")
        atts: dict[tuple, dict] = {}
        seen_hashes: set[str] = set()
        for a in attestations:
            key = _attestation_key(a)
            m, arb, rung = key
            pub = self._arbiter_pubs.get(arb)
            if pub is None:
                raise FundingInvalid("attesting arbiter unknown", m, arb, rung)
            if not verify_obj(a, pub):
                raise FundingInvalid("attestation signature invalid", m, arb, rung)
            if a.get("job_id") != info.job_id:
                raise FundingInvalid("attestation for a different job", m, arb, rung)
            if key in atts:
                raise FundingInvalid("duplicate attestation", m, arb, rung)
            if a["preimage_hash"] in seen_hashes:
                raise FundingInvalid(
                    "attested preimage hash reused — fee and rung locks must"
                    " be pairwise distinct (L15/§9.3)",
                    m,
                    arb,
                    rung,
                )
            seen_hashes.add(a["preimage_hash"])
            atts[key] = a

        outs: dict[tuple, dict] = {}
        for o in info.outputs:
            key = (o["milestone"], o["arbiter_id"], o["rung"])
            if key in outs:
                raise FundingInvalid("duplicate funded output", *key)
            outs[key] = o
        for key in atts:
            if key not in outs:
                raise FundingInvalid("attested output missing from funding", *key)
        for key in outs:
            if key not in atts:
                raise FundingInvalid("funded output has no attestation", *key)

        # Deterministic order (rung keys mix ints and the "fee" marker).
        def _order(key):
            m, arb, rung = key
            is_fee = rung == FEE_RUNG
            return (m, arb, is_fee, rung if isinstance(rung, int) else -1)

        ordered = sorted(outs, key=_order)
        for key in ordered:
            o, a = outs[key], atts[key]
            if o["amount_mc"] != a["amount_mc"]:
                raise FundingInvalid("amount differs from attestation", *key)
            if o["preimage_hash"] != a["preimage_hash"]:
                raise FundingInvalid(
                    "claimed lock hash differs from attestation", *key
                )
            if o["expiry"] != info.expiries[key[0]]:
                raise FundingInvalid("expiry differs from the schedule", *key)
            secret = self._secrets.get(key)
            if secret is not None and o["secret_hash"] != ledger_key(secret):
                raise FundingInvalid(
                    "output not keyed to our secret hash", *key
                )

        desc = self._client.descriptor()
        max_batch = desc["limits"]["max_batch"]
        hashes = [outs[key]["secret_hash"] for key in ordered]
        results = _status_chunked(self._client, hashes, max_batch)
        pinned: dict[tuple, dict] = {}
        for key, res in zip(ordered, results):
            o = outs[key]
            state = res.get("state")
            if state == "unknown":
                raise FundingInvalid("output not on the ledger", *key)
            if state != "unspent":
                raise FundingInvalid("output already spent", *key)
            if res.get("amount_mc") != o["amount_mc"]:
                raise FundingInvalid("on-ledger amount mismatch", *key)
            lock = res.get("lock")
            if not isinstance(lock, dict):
                raise FundingInvalid("output is not locked", *key)
            if lock.get("preimage_hash") != atts[key]["preimage_hash"]:
                raise FundingInvalid(
                    "funded lock hash does not equal the arbiter-attested"
                    " preimage hash",
                    *key,
                )
            if lock.get("expiry") != info.expiries[key[0]]:
                raise FundingInvalid("on-ledger expiry mismatch", *key)
            pinned[key] = {
                "amount_mc": o["amount_mc"],
                "secret_hash": o["secret_hash"],
                "preimage_hash": atts[key]["preimage_hash"],
                "expiry": o["expiry"],
            }
        # Pin only after EVERY check passed.
        self._pinned = pinned
        self._verified = True

    def redeem(self, m: int, reveals, allow_unverified: bool = False) -> int:
        """Claim every revealed output of milestone ``m`` that this
        instance holds a secret for, in ONE ``/v3/exchange`` call (one
        burn).  Each revealed preimage is checked against the PINNED
        (verified) lock hash before anything goes on the wire; a mismatch
        raises ``RevealInvalid`` naming the rung.

        Redeeming without a prior successful ``verify_funding`` is refused
        (the §9.3 check is mandatory); ``allow_unverified=True`` exists
        solely to model a negligent payee in tests (B3's sandboxed
        demonstration) and submits the reveals unchecked — the mint then
        adjudicates."""
        if not self._verified and not allow_unverified:
            raise EscrowError(
                "funding not verified — §9.3 mandates verify_funding before"
                " any work or redemption"
            )
        entries = []
        seen: set[tuple] = set()
        for r in reveals:
            if r.get("milestone") != m:
                continue
            arb = r.get("arbiter_id")
            for e in r.get("preimages", []):
                key = (m, arb, e["rung"])
                if key in seen:
                    continue
                secret = self._secrets.get(key)
                if secret is None:
                    continue
                preimage = b64u_decode(e["preimage"], expect_len=32)
                if self._verified:
                    pin = self._pinned.get(key)
                    if pin is None:
                        continue  # not part of the verified funding
                    if _sha256_b64u(preimage) != pin["preimage_hash"]:
                        raise RevealInvalid(
                            f"revealed preimage for milestone {m}, arbiter"
                            f" {arb!r}, rung {e['rung']} does not open the"
                            " verified funded lock"
                        )
                    amount = pin["amount_mc"]
                else:
                    amount = e["amount_mc"]
                seen.add(key)
                entries.append((key, secret, amount, preimage))
        if not entries:
            return 0
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        inputs = [
            {
                "token": format_token(self._mint_id, amount, secret),
                "witness": b64u_encode(preimage),
            }
            for _key, secret, amount, preimage in entries
        ]
        total = sum(amount for _k, _s, amount, _p in entries)
        burn = compute_burn(total, policy)
        net = total - burn
        fresh = new_secret()
        outputs = (
            [{"amount_mc": net, "secret_hash": ledger_key(fresh), "lock": None}]
            if net > 0
            else []
        )
        self._client.exchange(str(uuid.uuid4()), inputs, outputs)
        for key, _s, _a, _p in entries:
            self._secrets.pop(key, None)  # settled: the entry is spent
        if net > 0:
            self._holdings.append((fresh, net))
        return net


# ---------------------------------------------------------------------------
# CommitThenAccept — §9.4 micro-escrow
# ---------------------------------------------------------------------------


class CommitThenAccept:
    """One §9.4 commit-then-accept session (the sub-5-cent tier).

    One object models the session; the two parties' secrets live in
    strictly separate attributes and are generated by their own methods
    (L15): the worker's output secret in ``worker_hash``, the payer's
    acceptance preimage and refund secret in ``payer_commit``.  The funds
    are non-retractable until expiry even though the payer knows the
    preimage — it lacks the worker's output secret (§3.4, R1).

    Reveal deadline (requirement 6): ``payer_reveal`` refuses past
    ``expiry − grace_ms − redemption_margin`` — measured against the
    MINT's clock, never wall time — records the refusal, and raises
    ``LateReveal``; §10.2 treats it as a payer refusal.
    """

    def __init__(
        self,
        client,
        mint_id: str,
        redemption_margin_ms: int = 60_000,
        grace_ms: int | None = None,
    ):
        self._client = client
        self._mint_id = mint_id
        self._margin = _require_ms("redemption_margin", redemption_margin_ms, 1)
        self._grace_override = grace_ms
        # worker side
        self._worker_secret: bytes | None = None
        # payer side
        self._preimage: bytes | None = None
        self._refund_secret: bytes | None = None
        self._payer_holdings: list[tuple[bytes, int]] = []
        # agreed terms (set at commit)
        self.secret_hash: str | None = None
        self.amount_mc: int | None = None
        self.expiry: int | None = None
        self._grace_ms: int | None = None
        #: recorded refusals (late reveals) — §10.2 evidence (B6)
        self.refusals: list[dict] = []

    # -- worker side -----------------------------------------------------

    def worker_hash(self) -> str:
        """The worker generates and holds its fresh output secret; the
        payer only ever sees the hash (by-hash funding, §3.3)."""
        if self._worker_secret is not None:
            raise EscrowError("worker secret already generated")
        self._worker_secret = new_secret()
        return ledger_key(self._worker_secret)

    def worker_verify(self, amount_mc: int | None = None, expiry: int | None = None) -> None:
        """MANDATORY before working (§9.4): confirm the committed funds on
        the ledger — present, unspent, agreed amount, agreed expiry,
        locked.  Raises ``FundingInvalid`` otherwise (B6)."""
        if self._worker_secret is None:
            raise EscrowError("call worker_hash() first")
        amount = amount_mc if amount_mc is not None else self.amount_mc
        expected_expiry = expiry if expiry is not None else self.expiry
        if amount is None or expected_expiry is None:
            raise EscrowError("agreed amount/expiry unknown")
        h = ledger_key(self._worker_secret)
        _mt, results = self._client.status([h])
        res = results[0]
        if res.get("state") == "unknown":
            raise FundingInvalid("committed funds absent from the ledger")
        if res.get("state") != "unspent":
            raise FundingInvalid("committed output already spent")
        if res.get("amount_mc") != amount:
            raise FundingInvalid("committed amount differs from the agreement")
        lock = res.get("lock")
        if not isinstance(lock, dict):
            raise FundingInvalid("committed output is not locked")
        if lock.get("expiry") != expected_expiry:
            raise FundingInvalid("committed expiry differs from the agreement")

    def worker_redeem(self, preimage_b64u: str) -> int:
        """Claim with the worker's own secret + the revealed preimage,
        strictly before expiry (the mint enforces).  Returns the net."""
        if self._worker_secret is None or self.amount_mc is None:
            raise EscrowError("nothing committed")
        preimage = b64u_decode(preimage_b64u, expect_len=32)
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        burn = compute_burn(self.amount_mc, policy)
        net = self.amount_mc - burn
        fresh = new_secret()
        inputs = [
            {
                "token": format_token(
                    self._mint_id, self.amount_mc, self._worker_secret
                ),
                "witness": b64u_encode(preimage),
            }
        ]
        outputs = (
            [{"amount_mc": net, "secret_hash": ledger_key(fresh), "lock": None}]
            if net > 0
            else []
        )
        self._client.exchange(str(uuid.uuid4()), inputs, outputs)
        return net

    # -- payer side ------------------------------------------------------

    def payer_commit(
        self,
        hash_from_worker: str,
        amount_mc: int,
        expiry: int,
        funding_tokens: list[str],
    ) -> None:
        """Fund a by-hash output at the worker's hash, locked to the
        payer's OWN fresh acceptance preimage with a short expiry (§9.4)."""
        if self._preimage is not None:
            raise EscrowError("already committed")
        if type(amount_mc) is not int or amount_mc <= 0:
            raise EscrowError("amount_mc must be a positive integer")
        _require_ms("expiry", expiry, 1)
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        grace = (
            self._grace_override
            if self._grace_override is not None
            else desc["lock_params"]["grace_ms"]
        )
        self._preimage = new_secret()
        self._refund_secret = new_secret()
        input_sum = 0
        for t in funding_tokens:
            tok = parse_token(t)
            if tok.mint_id != self._mint_id:
                raise EscrowError("funding token from a different mint")
            input_sum += tok.amount_mc
        burn = compute_burn(input_sum, policy)
        change = input_sum - amount_mc - burn
        if change < 0:
            raise EscrowError("funding tokens do not cover amount + burn")
        outputs = [
            {
                "amount_mc": amount_mc,
                "secret_hash": hash_from_worker,
                "lock": {
                    "preimage_hash": _sha256_b64u(self._preimage),
                    "expiry": expiry,
                    "refund_hash": _sha256_b64u(self._refund_secret),
                },
            }
        ]
        change_secret = None
        if change > 0:
            change_secret = new_secret()
            outputs.append(
                {
                    "amount_mc": change,
                    "secret_hash": ledger_key(change_secret),
                    "lock": None,
                }
            )
        self._client.exchange(str(uuid.uuid4()), list(funding_tokens), outputs)
        if change_secret is not None:
            self._payer_holdings.append((change_secret, change))
        self.secret_hash = hash_from_worker
        self.amount_mc = amount_mc
        self.expiry = expiry
        self._grace_ms = grace

    def reveal_deadline(self) -> int:
        """§9.4: ``expiry − grace_ms − redemption_margin``."""
        if self.expiry is None or self._grace_ms is None:
            raise EscrowError("nothing committed")
        return self.expiry - self._grace_ms - self._margin

    def payer_reveal(self) -> str:
        """Reveal acceptance: return the preimage — but ONLY up to the
        reveal deadline (checked against the mint clock).  A later reveal
        would trap the worker against the §3.4 grace convention, so it
        raises ``LateReveal`` and is recorded as a refusal (§10.2)."""
        if self._preimage is None:
            raise EscrowError("nothing committed")
        deadline = self.reveal_deadline()
        mint_time, _results = self._client.status([])
        if mint_time > deadline:
            refusal = {
                "kind": "late_reveal",
                "party": "payer",
                "secret_hash": self.secret_hash,
                "mint_time": mint_time,
                "reveal_deadline": deadline,
                "expiry": self.expiry,
            }
            self.refusals.append(refusal)
            raise LateReveal(
                f"reveal at mint_time {mint_time} is past the deadline"
                f" {deadline} (expiry − grace_ms − redemption_margin);"
                " recorded as a payer refusal (§9.4/§10.2)"
            )
        return b64u_encode(self._preimage)

    def payer_refund(self) -> int:
        """Refund path at/after expiry (mint-enforced).  Returns the net."""
        if self._refund_secret is None or self.amount_mc is None:
            raise EscrowError("nothing committed")
        desc = self._client.descriptor()
        policy = _policy_from_descriptor(desc)
        burn = compute_burn(self.amount_mc, policy)
        net = self.amount_mc - burn
        fresh = new_secret()
        inputs = [
            {
                "hash": self.secret_hash,
                "witness": b64u_encode(self._refund_secret),
            }
        ]
        outputs = (
            [{"amount_mc": net, "secret_hash": ledger_key(fresh), "lock": None}]
            if net > 0
            else []
        )
        self._client.exchange(str(uuid.uuid4()), inputs, outputs)
        if net > 0:
            self._payer_holdings.append((fresh, net))
        return net


# ---------------------------------------------------------------------------
# dispute-outcome records (via C12)
# ---------------------------------------------------------------------------


def make_dispute_record(
    job_id: str,
    milestone: int,
    claimed_mc: int,
    released_mc: int,
    arbiter_ids: list,
    evidence,
    timestamp: int,
    votes: list,
    refusals=(),
) -> dict:
    """Build the §10.2 dispute-outcome record for an escrow milestone via
    C12: the decision is derived from claimed vs released amounts
    ("released" / "refunded" / "split"), the signed vote set is attached
    as mandatory panel evidence (L15), and party refusals are recorded."""
    if released_mc == claimed_mc:
        decision = "released"
    elif released_mc == 0:
        decision = "refunded"
    else:
        decision = "split"
    return _c12_make_dispute_record(
        job_id,
        milestone,
        claimed_mc,
        released_mc,
        decision,
        list(arbiter_ids),
        evidence_hash(evidence),
        timestamp,
        list(votes),
        refusals=list(refusals),
    )
