"""C01 — tokencodec: pure encoding layer (spec §3.1–§3.4).

Token strings, base64url secrets/hashes, ledger keys, canonical JSON.
No I/O, no state, no clock.  Tokens are passwords (§3.1): nothing in this
module writes, prints, or records secret material anywhere.
"""

import base64
import hashlib
import os
import re
import unicodedata
from typing import NamedTuple

__all__ = [
    "MINT_ID_RE",
    "TokenError",
    "Token",
    "b64u_encode",
    "b64u_decode",
    "new_secret",
    "ledger_key",
    "format_token",
    "parse_token",
    "canonical_json",
    "body_digest",
]

SECRET_LEN = 32
TOKEN_PREFIX = "aicash"
TOKEN_VERSION = "v3"

MINT_ID_RE = re.compile(r"^[a-z0-9-]{1,64}$")
"""The §3.1 mint-id rule, as the compiled regex this module enforces.

A valid mint_id is 1–64 characters drawn from lowercase ASCII letters,
digits, and hyphen (``^[a-z0-9-]{1,64}$``). Exported so other components
(C06 config validation, C12 envelopes, operator tooling) can validate a
mint_id with the exact same rule token parsing applies — never a
re-typed copy of the pattern."""
_AMOUNT_RE = re.compile(r"^[1-9][0-9]*$")  # positive decimal, no leading zeros
_B64U_ALPHABET_RE = re.compile(r"^[A-Za-z0-9_-]*$")


class TokenError(ValueError):
    """Raised on any malformed token / encoding input."""

    def __init__(self, message: str, reason: str = "bad_format"):
        super().__init__(message)
        self.reason = reason


class Token(NamedTuple):
    mint_id: str
    amount_mc: int
    secret: bytes


def b64u_encode(b: bytes) -> str:
    """base64url without padding (§3.1)."""
    if not isinstance(b, bytes):
        raise TokenError("b64u_encode requires bytes")
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def b64u_decode(s: str, expect_len: int | None = None) -> bytes:
    """Strict base64url-no-padding decode.

    Rejects: non-str input, `=` padding, `+`/`/` (standard-alphabet) chars,
    whitespace or any other character outside [A-Za-z0-9_-], impossible
    lengths (len % 4 == 1), non-canonical encodings (nonzero trailing bits),
    and — when ``expect_len`` is given — any decoded length other than it.
    """
    if not isinstance(s, str):
        raise TokenError("b64u_decode requires str")
    if not _B64U_ALPHABET_RE.fullmatch(s):
        raise TokenError("invalid base64url character")
    if len(s) % 4 == 1:
        raise TokenError("invalid base64url length")
    pad = (-len(s)) % 4
    try:
        raw = base64.urlsafe_b64decode(s + "=" * pad)
    except Exception as exc:  # pragma: no cover - alphabet/length already checked
        raise TokenError("invalid base64url") from exc
    # Canonicality: re-encoding must reproduce the input exactly (rejects
    # nonzero trailing bits, so each byte string has exactly one encoding).
    if base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii") != s:
        raise TokenError("non-canonical base64url")
    if expect_len is not None and len(raw) != expect_len:
        raise TokenError(
            "decoded length %d, expected %d" % (len(raw), expect_len)
        )
    return raw


def new_secret() -> bytes:
    """32 random bytes from os.urandom (§3.1: generated by the holder)."""
    return os.urandom(SECRET_LEN)


def ledger_key(secret: bytes) -> str:
    """b64u(sha256(raw 32 secret bytes)) — the ledger key encoding (§3.2)."""
    if not isinstance(secret, bytes):
        raise TokenError("ledger_key requires bytes")
    if len(secret) != SECRET_LEN:
        raise TokenError("secret must be exactly 32 bytes")
    return b64u_encode(hashlib.sha256(secret).digest())


def _check_mint_id(mint_id: object) -> str:
    if not isinstance(mint_id, str) or not MINT_ID_RE.fullmatch(mint_id):
        raise TokenError("invalid mint_id")
    return mint_id


def format_token(mint_id: str, amount_mc: int, secret: bytes) -> str:
    """"aicash:v3:<mint>:<amt>:<b64u secret>" (§3.1)."""
    _check_mint_id(mint_id)
    if isinstance(amount_mc, bool) or not isinstance(amount_mc, int):
        raise TokenError("amount_mc must be an int")
    if amount_mc <= 0:
        raise TokenError("amount_mc must be positive")
    if not isinstance(secret, bytes):
        raise TokenError("secret must be bytes")
    if len(secret) != SECRET_LEN:
        raise TokenError("secret must be exactly 32 bytes")
    return "%s:%s:%s:%d:%s" % (
        TOKEN_PREFIX,
        TOKEN_VERSION,
        mint_id,
        amount_mc,
        b64u_encode(secret),
    )


def parse_token(s: str) -> Token:
    """Parse a token string; raises TokenError('bad_format') on anything off."""
    if not isinstance(s, str):
        raise TokenError("token must be a string")
    parts = s.split(":")
    if len(parts) != 5:
        raise TokenError("token must have exactly 5 colon-separated fields")
    prefix, version, mint_id, amount_str, secret_str = parts
    if prefix != TOKEN_PREFIX:
        raise TokenError("bad token prefix")
    if version != TOKEN_VERSION:
        raise TokenError("bad token version")
    _check_mint_id(mint_id)
    if not _AMOUNT_RE.fullmatch(amount_str):
        raise TokenError("invalid amount")
    amount_mc = int(amount_str)
    secret = b64u_decode(secret_str, expect_len=SECRET_LEN)
    return Token(mint_id=mint_id, amount_mc=amount_mc, secret=secret)


# ---------------------------------------------------------------------------
# Canonical JSON (§3.3, pinned; OPEN-QUESTIONS R21, normalize-then-sort):
# UTF-8; all strings (keys and values) NFC-normalized FIRST, then object
# keys sorted by Unicode code point on the NORMALIZED key; two distinct raw
# keys that collide after NFC are rejected; no insignificant whitespace,
# plain decimal integers (no floats anywhere).
# ---------------------------------------------------------------------------

_STRING_ESCAPES = {
    '"': '\\"',
    "\\": "\\\\",
    "\b": "\\b",
    "\f": "\\f",
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def _canon_string(s: str) -> str:
    s = unicodedata.normalize("NFC", s)
    out = ['"']
    for ch in s:
        esc = _STRING_ESCAPES.get(ch)
        if esc is not None:
            out.append(esc)
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _canon(obj) -> str:
    if obj is None:
        return "null"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    if isinstance(obj, int):
        return str(obj)
    if isinstance(obj, float):
        raise TokenError("floats are forbidden in canonical JSON")
    if isinstance(obj, str):
        return _canon_string(obj)
    if isinstance(obj, (list, tuple)):
        return "[" + ",".join(_canon(item) for item in obj) + "]"
    if isinstance(obj, dict):
        for key in obj:
            if not isinstance(key, str) or isinstance(key, bool):
                raise TokenError("canonical JSON object keys must be strings")
        # Normalize-then-sort (requirement 6; §3.3 R21): NFC-normalize every
        # key FIRST, reject distinct raw keys that collide after NFC, then
        # sort by Unicode code point on the *normalized* key; Python's
        # default str ordering is exactly code-point order.
        norm_items = []
        seen = set()
        for key in obj:
            norm_key = unicodedata.normalize("NFC", key)
            if norm_key in seen:
                raise TokenError(
                    "duplicate object key after NFC normalization"
                )
            seen.add(norm_key)
            norm_items.append((norm_key, obj[key]))
        norm_items.sort(key=lambda item: item[0])
        pieces = [
            _canon_string(norm_key) + ":" + _canon(value)
            for norm_key, value in norm_items
        ]
        return "{" + ",".join(pieces) + "}"
    raise TokenError(
        "type %s is not representable in canonical JSON" % type(obj).__name__
    )


def canonical_json(obj) -> bytes:
    """§3.3 pinned canonical JSON as UTF-8 bytes."""
    return _canon(obj).encode("utf-8")


def body_digest(obj) -> str:
    """b64u(sha256(canonical_json(obj))) (§3.3 idempotency digests)."""
    return b64u_encode(hashlib.sha256(canonical_json(obj)).digest())
